public class DNAToRNA {
    public static void main(String[] args) {

        // Given DNA dataset
        String dna = "GCGTACTGGGGATGGAGCATTATAAGACAGGGAAAGCTCATCGACTGAACTGCTCCGTACGGGTTTTAGCTGGGTTCAGGTCGCTGACCTATGCCAATTCAACCTTGCTGAGCCGGCGTGGCACCCTATGGAAGACGCGGAGCTACGTCCCCACTATACGAAAATTAGAGCTCAACGCCGGAGCTTGCTTTTGATCCAGCAGATTCAGGCGAGACCGAGGGTGAGCCGTAGGCTTCTCGCAATTGGTACGATCCGCGCGTCGTTCTTTGATGGAAAGAACCGTGGGCCAAATAACCAGCAGTATAATCGCCTGTTTGCTAGAAGCTATACTTAGTCTTGGTGCGACATACTGATTAAAATGCAATGTCTGCCCGGGATTACCGCGTAAGATCACGATCGCTCATTTCGTTAATCTGGGATTTGCCCACCATTATCGATCAGAATATCTATGGTTTGATACGAACATGTGTCCAGGCTGTAAAGCTAAGAGATGTTTTAGGAGGGTGCAGCTACATGAAATCCACAGCTTATTGAGATGTATTTATCATAGATGGCACTAACGGCACCAACGCACGTGATAGCCTCTCACACTCCCTTCGGGGTGGGCCGATAGAGGCTGCGGAAGAACAGCCGTTCATTTAGGTGCTTAAACCGCCAACTTCATTGCGGCTTGAGGTGGTTGAATTCGAGTCATAATGTACAACTTCATCAGTCCGATTTAGGTACTTGAAACGGTATTGAGGTCATCGCAGTAGAGTCACTTGAACAACCTTGCCAAACATTCCTACAGGCCTTAAGGACCCGGGGATAACCCTGCCGCACAAGGCCAAACACTTAACATACCTCGGCAGCAACGATGCCTAATCTAATTTACCCCAGGTAGTACGTTACAGGGCTGGACCTTAAGAAAATCAGTGGCAGAAGACGCACTACAGTGAACGGAGTTCATCTCCCGCCCGCACTGAGACTTTCTCTCCGA";

        // Transcribe DNA to RNA (T → U)
        String rna = dna.replace('T', 'U');

        // Output the RNA string
        System.out.println(rna);
    }
}
