public class ReverseComplement {
    public static void main(String[] args) {

        // Given DNA dataset
        String dna =
            "CGTGGGTCTAAGTCTGCGTCCAACACGGCGCAGGCGTGTTCGGATTCATGTGGCAACCAGAACTCCGGCCCAGAGGCTAGAAACTTCGAATAGAAACCCCCATATCGGATAGTACTTTCGAAGCTAGTAGCGCACAGAGCGGGGATGCGCATTCACCAATGCAGTCCGCTTCACTACCGGCACGGAATACACTTACTCAGTTTGGTCCCCAGCCGACTCCGGGTTATTGTTAAGTCATACACGTAAACGTGCTTCGTATGACTTGAGAACAACAAATTCTATCTGTCGAAGAAGCTTTCATACGCCGTTGCTCGGCTGTAGTGGCAACTGAACGTAACGCCATGTTTCCGCCGAGCTTGACCGGGCGTCGTGTTATTGTTTAATACAAGCACTTTACTTAGAACACCAAAAGGCATCCTAGCCTAGTGGATAGACCGAGTACCCAACAAAGCCAAACGTCCAAAATATCTGCTACATGCTACGACAACATCAGACATTAGCCGACTTCGCCGGTGTCGGTAGGTAAGACACGCTCCACATATCCCCGGGTTACGCATGACTGAGGCGTCCCGATTAGACGCCCGGTCTGTCGCCCTCGATTTCATTCTGAAGACCGAATAATTCTCCGCTACATGAGGTGAGCCCGTATCTTTTAGTGTGGGGCACCGCGGTGCCGGCCGTCCTATGACCCCGAGGTCGATAGGGCAGGGTTGAGCACTGCATTTTCTAGCCACGGGTCATACATAGGGCGCCCGCCGGCATACCCCTTCTCTATGATTGCCAACAAAAAGCAGTCAGCGCGCACTTGCCATAGTTCTTCTCCTACTCTAGACACGCCACATACAGTGGACATGGTGCGCTTTTGTCG";

        StringBuilder reverseComplement = new StringBuilder();

        // Traverse the DNA string backwards
        for (int i = dna.length() - 1; i >= 0; i--) {
            char base = dna.charAt(i);

            // Append complementary base
            if (base == 'A') {
                reverseComplement.append('T');
            } else if (base == 'T') {
                reverseComplement.append('A');
            } else if (base == 'C') {
                reverseComplement.append('G');
            } else if (base == 'G') {
                reverseComplement.append('C');
            }
        }

        // Output the reverse complement
        System.out.println(reverseComplement.toString());
    }
}
