public class DNACount {
    public static void main(String[] args) {

        String s = "GATACAAAGTCGGCCATCTTACGTTCAATGAATGTGGCATTATCGATTATCGTAGACACACATCCTGTGGCCGCCCCAGCGATTCGCCCCCATTAGAATGAACATAGGCACAATACATGAGTCTCTTCATGAATAGATCCCAGTGGTTATAAAGTGTGTCAAGCTCCCGTCTCGGCCTATGGCTAATCGCCAATGGAAACCGTGGAACCGTCCGTTGGACGATTTTACGGGAACAACATACACACGGGAATAGCCTACCCAACGAGGCTACTGTGCCACAGTGGTTGGGTTGTGCTACACGTACGATCCACGGAGTGAAAAATTTAGGAGCTCAAACAAAAATAAGACTGATTAGTATTACTTGTATGGGGTTAAGCACGTTGTTGAGCTCCCACGTCTGAAACGTGGTAGCGCCGCTCTTTGAGACTGAAACAGTTTGTAGGTCAGGCACAGGAGCATAGGGGGAAAGGAAAACACGTGCTTGACGGAGTAGGAGCCCCAATATTTCTGAAATGTGTTGCCAATCAGCGTGACCTTCAATGAGTACTAACCGGAGGGTATGCTCAATGCTCAGGCGTGTGGCATGGGCACGCATCTATTAGCAGTCCCGATAGAGACCTGTCCAGTCCTATACAGCTACGCTACTATGGCGGAGCATAAGGGCATGGGATCCGCGTATCCATACTTCCTCCAATTGCTGTACATTGGCGACTTAGTTTTTCGTAAGGGATGTAATAGATAAAAGATTACACCCAGTCCGTACACAAGCACTACGTACATTATCTTGGGGGATTATGTAAGAACACGAACTCTCAGATATGGTCCACATCTCGCGCGCATGCTTAAAGCATAGGTTTCTATTACGGGTAGACTCTAGGCAGTTTCTGCATTTAGATTGTGATCTAGTGGAGGAACGAGGAGCGCATGAGACTGTAGTTGTCGCCAGAATGGTCAGCCAAAGTGAACTGCC";

        int countA = 0;
        int countC = 0;
        int countG = 0;
        int countT = 0;

        for (int i = 0; i < s.length(); i++) {
            char nucleotide = s.charAt(i);

            if (nucleotide == 'A') {
                countA++;
            } else if (nucleotide == 'C') {
                countC++;
            } else if (nucleotide == 'G') {
                countG++;
            } else if (nucleotide == 'T') {
                countT++;
            }
        }

        System.out.println(countA + " " + countC + " " + countG + " " + countT);
    }
}
